// COUNTER
export const SAVING_MY_PROFILE = 'SAVING_MY_PROFILE';

export const GET_MY_PROFILE = 'GET_MY_PROFILE';
export const GET_MY_PROFILE_SUCCESS = 'GET_MY_PROFILE_SUCCESS';
export const GET_MY_PROFILE_FAILED = 'GET_MY_PROFILE_FAILED';
